language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - cat /etc/apt/sources.list
    - echo "deb http://efever-oss.s3-website-us-west-1.amazonaws.com/deb/ amd64/" | sudo tee -a /etc/apt/sources.list
    - sudo add-apt-repository --yes ppa:beineri/opt-qt532
    - cat /etc/apt/sources.list
    - sudo apt-get update -qq
    - apt-cache search qt5
    - sudo apt-get install --force-yes -qq qt53quickcontrols  qt53declarative qt53script qt53graphicaleffects qpm
    - sh -e /etc/init.d/xvfb start
script:
    - source /opt/qt53/bin/qt53-env.sh 
    - cd tests/qsyncableunittests
    - qpm install
    - qmake
    - make
    - ls
    - ./qsyncableunittests
  
