language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm    
    - sudo apt-get update
    - apt-cache search qt5
    - sudo apt-get install --force-yes -qq qt55quickcontrols  qt55declarative qt55script qt55graphicaleffects qpm valgrind
    - sh -e /etc/init.d/xvfb start
script:
    - source /opt/qt55/bin/qt55-env.sh 
    - cd tests/qsyncableunittests
    - qpm install
    - qmake
    - make
    - ls
    - ./qsyncableunittests
    - valgrind --leak-check=full --show-reachable=yes ./qsyncableunittests QSyncableTests
  
